### PR TITLE
Fix #104: Crash from Tesseract while scrolling a list in Minecolonies

### LINKED ISSUE #104: Crash from Tesseract while scrolling a list in Minecolonies
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest BlockUI Version?

- [X] I am running the latest **beta/release** version of BlockUI for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Minecraft Version

1.21

### BlockUI Version

1.0.192

### Current Behavior

I was scrolling down the restaurant menu in Minecolonies, trying to find out what recipes I could add to the menu, when it suddenly crashed!

### Expected Behavior

Just to keep scrolling!

### Reproduction Steps

1. Open ATM10 v 1.20
2. Get your colony going, with a restaurant and cookery
3. Scroll the menu list. This will take a while due to Pam's.

### Logs

https://gist.github.com/Mijithemidge/f1f7b102f4cb61967c27d6407651b7b1

### Anything else?

https://gist.github.com/Mijithemidge/0142a11698a835c20f1aa128c415e511 Crash Report

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Swedz**
Closes #104 

I was not able to get the project to load properly on IntelliJ due to quite a few odd issues with the build.gradle, but this is simple enough and should work. Make sure to test before merging.

### CODE REVIEW

File: src/main/java/com/ldtteam/blockui/controls/AbstractTextElement.java [hunk 1]
```diff
@@ -492,10 +492,9 @@ public MutableComponent getText()
         return isTextEmpty() ? null : text.get(0);
     }
 
-    @SuppressWarnings({"unchecked", "rawtypes"})
     public void setTextOld(final List<Component> text)
     {
-        setText((List<MutableComponent>)((List) text));
+        setText(text.stream().map(c -> c instanceof MutableComponent m ? m : c.copy()).toList());
```
Comment (Thodor12) [inline src/main/java/com/ldtteam/blockui/controls/AbstractTextElement.java:497]: I'm not sure if the instanceof is strictly necessary. It's a minor optimization, I would be fine with calling copy by default.

So
```java
setText(text.stream().map(Component::copy).toList());
```

Same for below

**Review by Thodor12 — APPROVED** [review]
Thanks for your contribution, changes look fine to me but I have one remark

**Review by Nightenom — APPROVED** [review]

File: src/main/java/com/ldtteam/blockui/controls/AbstractTextElement.java (hunk 1 above)
Comment (Nightenom) [reply src/main/java/com/ldtteam/blockui/controls/AbstractTextElement.java:497]: This is fine, I will clean up in next porting window if necessary

**Comment by Nightenom** [comment]
I will merge this later, we need to update gradle infrastructure first

**Comment by Nightenom** [comment]
@Swedz could you please rebase/merge from main branch?
